---
- hosts: blockchain
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Update all installed packages using YUM module
      yum:
        name: '*'
        state: latest
        update_cache: yes
        update_only: yes
    - name: Appending the group 'docker' to the user 'ec2-user' groups
      user:
        name: ec2-user
        groups: docker
        append: yes
    - name: Install a list of packages for Docker
      yum:
        name:
          - yum-utils
          - docker
        state: present
    - name: Install docker-compose from official github repo
      get_url:
        url : https://github.com/docker/compose/releases/download/2.10.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
    - name: Start Docker
      service:
        name: "docker"
        enabled: true
        state: started
  # - name: Nginx Install 
  #   apt:
  #     name: nginx
  #     state: present
  #     update_cache: yes

  # - hostname:
  #     name: web01

  # - name: Copiando index.html personalizado
  #   copy:
  #     src: index.html
  #     dest: /var/www/html/index.html
  #   notify: Restart

  # - name: restart nginx
  #   service:
  #     name: nginx
  #     state: restarted


  # handlers: 
  # - name: Restart
  #   service:
  #     name: nginx
  #     state: restarted